import type { SourceRef, SymptomGuide } from "./types"

export const OFFICIAL_SOURCES: SourceRef[] = [
  {
    id: "nfa-cpr",
    institution: "소방청",
    title: "심폐소생술(CPR)",
    url: "https://www.nfa.go.kr/nfa/safetyinfo/lifesafety/0001/?boardId=bbs_0000000000002462&category=%EC%9D%91%EA%B8%89%EC%B2%98%EC%B9%98&cntId=3&mode=view&pageIdx=",
    note: "119구급대원 현장응급처치 표준지침 기반",
  },
  {
    id: "nfa-aed",
    institution: "소방청",
    title: "자동 심장충격기(AED)",
    url: "https://www.nfa.go.kr/nfa/safetyinfo/lifesafety/0001/?boardId=bbs_0000000000002462&category=%EC%9D%91%EA%B8%89%EC%B2%98%EC%B9%98&cntId=4&mode=view&pageIdx=",
    note: "AED 전원, 패드 부착, 리듬 분석, 충격 후 CPR 재개 절차",
  },
  {
    id: "nfa-choking",
    institution: "소방청",
    title: "기도폐쇄",
    url: "https://www.nfa.go.kr/nfa/safetyinfo/lifesafety/0001/?boardId=bbs_0000000000002462&category=%EC%9D%91%EA%B8%89%EC%B2%98%EC%B9%98&cntId=6&mode=view&pageIdx=",
    note: "기침 격려, 등 두드리기와 복부 밀어내기, 의식 소실 시 CPR",
  },
  {
    id: "nfa-bleeding",
    institution: "소방청",
    title: "지혈 처치",
    url: "https://www.nfa.go.kr/nfa/safetyinfo/lifesafety/0001/?boardId=bbs_0000000000002462&category=%EC%9D%91%EA%B8%89%EC%B2%98%EC%B9%98&cntId=11&mode=view&pageIdx=",
    note: "거즈 직접 압박, 붕대 고정, 손상 부위 거상",
  },
  {
    id: "nfa-burn",
    institution: "소방청",
    title: "화상 처치",
    url: "https://www.nfa.go.kr/nfa/safetyinfo/lifesafety/0001/?boardId=bbs_0000000000002462&category=%EC%9D%91%EA%B8%89%EC%B2%98%EC%B9%98&cntId=12&mode=view&pageIdx=",
    note: "장신구 제거, 흐르는 물로 냉각, 물집 보존",
  },
  {
    id: "nfa-seizure",
    institution: "소방청",
    title: "경련처치",
    url: "https://www.nfa.go.kr/nfa/safetyinfo/lifesafety/0001/?boardId=bbs_0000000000002462&category=%EC%9D%91%EA%B8%89%EC%B2%98%EC%B9%98&cntId=19&mode=view&pageIdx=",
    note: "119구급대원 현장응급처치 표준지침 기반",
  },
  {
    id: "nfa-heat",
    institution: "소방청",
    title: "열손상",
    url: "https://www.nfa.go.kr/nfa/safetyinfo/lifesafety/0001/?boardId=bbs_0000000000002462&category=%EC%9D%91%EA%B8%89%EC%B2%98%EC%B9%98&cntId=16&mode=view&pageIdx=",
    note: "시원한 곳 이동, 복장 제거, 체온 낮추기, 고체온 시 119",
  },
  {
    id: "nfa-cold",
    institution: "소방청",
    title: "한랭손상",
    url: "https://www.nfa.go.kr/nfa/safetyinfo/lifesafety/0001/?boardId=bbs_0000000000002462&category=%EC%9D%91%EA%B8%89%EC%B2%98%EC%B9%98&cntId=17&mode=view&pageIdx=",
    note: "따뜻한 곳 이동, 젖은 옷 제거, 보온, 마사지 금지",
  },
  {
    id: "nfa-sting",
    institution: "소방청",
    title: "벌 쏘임",
    url: "https://www.nfa.go.kr/nfa/safetyinfo/lifesafety/0001/?boardId=bbs_0000000000002462&category=%EC%9D%91%EA%B8%89%EC%B2%98%EC%B9%98&cntId=8&mode=view&pageIdx=",
    note: "카드 모서리로 침 제거, 세척, 얼음찜질, 전신반응 주의",
  },
  {
    id: "nfa-snake",
    institution: "소방청",
    title: "뱀 물림",
    url: "https://www.nfa.go.kr/nfa/safetyinfo/lifesafety/0001/?boardId=bbs_0000000000002462&category=%EC%9D%91%EA%B8%89%EC%B2%98%EC%B9%98&cntId=9&mode=view&pageIdx=",
    note: "환자 안정, 움직임·말하기 자제, 독 흡입 금지",
  },
  {
    id: "nfa-nosebleed",
    institution: "소방청",
    title: "코피 처치",
    url: "https://www.nfa.go.kr/nfa/safetyinfo/lifesafety/0001/?boardId=bbs_0000000000002462&category=%EC%9D%91%EA%B8%89%EC%B2%98%EC%B9%98&cntId=10&mode=view&pageIdx=",
    note: "앉아서 고개 숙이기, 코 앞쪽 압박, 피 삼키지 않기",
  },
  {
    id: "kdca-anaphylaxis",
    institution: "질병관리청 국가건강정보포털",
    title: "아나필락시스 응급처치",
    url: "https://health.kdca.go.kr/healthinfo/biz/health/ntcnInfo/healthSourc/thtimtCntnts/thtimtCntntsView.do?thtimt_cntnts_sn=81",
    note: "원인 제거, 눕히기, 의식·호흡·맥박 확인, 119 신고, 자가주사용 에피네프린",
  },
]

export const SYMPTOMS: SymptomGuide[] = [
  {
    id: "head-injury",
    name: "머리 부딪힘",
    shortLabel: "머리 부딪힘",
    keywords: ["머리", "두부", "부딪", "넘어짐", "두통", "구토", "혹"],
    emergencyLevel: "soon",
    recommendedDepartments: ["신경외과", "응급의학과"],
    firstAidSteps: [
      "앉거나 누워서 안정을 취하고 머리·목을 크게 움직이지 마세요.",
      "의식, 말투, 반복 구토, 심한 두통이 있는지 확인하세요.",
      "증상이 악화되거나 위험 신호가 있으면 119 또는 응급실로 이동하세요.",
    ],
    warningSigns: ["의식저하", "반복 구토", "심한 두통", "경련", "한쪽 팔다리 힘 빠짐"],
    avoidActions: ["억지로 일으켜 세우기", "졸리다고 혼자 재우기", "통증을 참고 운전하기"],
    sourceIds: ["nfa-cpr"],
  },
  {
    id: "cut-bleeding",
    name: "베임/출혈",
    shortLabel: "베임/출혈",
    keywords: ["베임", "상처", "출혈", "피", "찢어짐", "칼", "유리", "물림"],
    emergencyLevel: "soon",
    recommendedDepartments: ["외과", "응급의학과"],
    firstAidSteps: [
      "깨끗한 거즈나 천으로 상처를 직접 눌러 지혈하세요.",
      "가능하면 상처 부위를 심장보다 높게 유지하세요.",
      "깊거나 오염된 상처, 동물에 물린 상처는 빠르게 진료를 받으세요.",
    ],
    warningSigns: ["10분 이상 지혈 안 됨", "깊은 상처", "동물에 물림", "감각저하", "피가 솟구침"],
    avoidActions: ["상처 안쪽을 손으로 만지기", "박힌 물체 빼기", "민간요법 바르기"],
    sourceIds: ["nfa-bleeding"],
  },
  {
    id: "burn",
    name: "화상",
    shortLabel: "화상",
    keywords: ["화상", "데임", "데였", "뜨거운", "물집", "전기", "화학"],
    emergencyLevel: "soon",
    recommendedDepartments: ["응급의학과", "외과", "피부과"],
    firstAidSteps: [
      "흐르는 시원한 물로 15~20분 정도 식히세요.",
      "반지, 시계처럼 조이는 물건은 붓기 전에 제거하세요.",
      "깨끗한 천으로 덮고 얼굴·손·넓은 화상은 응급 진료를 받으세요.",
    ],
    warningSigns: ["얼굴·목 화상", "손·발·관절 화상", "넓은 물집", "전기·화학 화상", "호흡곤란"],
    avoidActions: ["얼음 직접 대기", "물집 터뜨리기", "치약·기름·연고 임의 도포"],
    sourceIds: ["nfa-burn"],
  },
  {
    id: "chest-pain",
    name: "흉통",
    shortLabel: "흉통",
    keywords: ["흉통", "가슴", "심장", "쥐어짜", "식은땀", "압박감"],
    emergencyLevel: "urgent",
    recommendedDepartments: ["응급의학과", "심장내과"],
    firstAidSteps: [
      "움직이지 말고 편한 자세로 앉거나 기대세요.",
      "가슴 통증과 함께 식은땀, 호흡곤란, 어지러움이 있으면 즉시 119에 전화하세요.",
      "복용 중인 심장약이 있다면 119 상담 또는 처방 지시에 따르세요.",
    ],
    warningSigns: ["식은땀", "호흡곤란", "왼팔·턱 통증", "실신 느낌", "10분 이상 지속"],
    avoidActions: ["직접 운전하기", "혼자 있기", "통증이 사라질 때까지 무작정 기다리기"],
    sourceIds: ["nfa-cpr"],
  },
  {
    id: "breathing-difficulty",
    name: "호흡곤란",
    shortLabel: "호흡곤란",
    keywords: ["호흡곤란", "숨", "숨쉬기", "쌕쌕", "천식", "청색증", "질식"],
    emergencyLevel: "urgent",
    recommendedDepartments: ["응급의학과", "호흡기내과", "알레르기내과"],
    firstAidSteps: [
      "상체를 세우고 꽉 끼는 옷을 느슨하게 하세요.",
      "말하기 어렵거나 입술이 파래지면 즉시 119에 전화하세요.",
      "처방받은 흡입기나 알레르기 응급약은 본인 처방대로 사용하세요.",
    ],
    warningSigns: ["말하기 어려움", "입술·손끝이 파래짐", "의식저하", "얼굴·혀 부음", "흉통 동반"],
    avoidActions: ["종이봉투 재호흡", "눕혀서 방치", "처방 없는 약 임의 복용"],
    sourceIds: ["nfa-choking", "kdca-anaphylaxis"],
  },
  {
    id: "abdominal-pain",
    name: "복통",
    shortLabel: "복통",
    keywords: ["복통", "배", "우하복부", "혈변", "설사", "구토", "명치"],
    emergencyLevel: "soon",
    recommendedDepartments: ["내과", "소화기내과", "응급의학과"],
    firstAidSteps: [
      "무리하게 먹거나 마시지 말고 편한 자세로 쉬세요.",
      "통증 위치, 시작 시간, 구토·설사·발열 여부를 확인하세요.",
      "극심한 통증이나 혈변, 우하복부 통증은 응급실 진료를 권장합니다.",
    ],
    warningSigns: ["극심한 통증", "우하복부 통증", "혈변", "반복 구토", "복부가 딱딱함"],
    avoidActions: ["진통제부터 먹고 버티기", "찜질로 계속 참기", "음식 억지로 먹기"],
    sourceIds: [],
  },
  {
    id: "fracture",
    name: "골절 의심",
    shortLabel: "골절 의심",
    keywords: ["골절", "부러", "금간", "삠", "탈구", "통증", "변형", "붓기"],
    emergencyLevel: "soon",
    recommendedDepartments: ["정형외과", "응급의학과"],
    firstAidSteps: [
      "다친 부위를 움직이지 않게 하고 편한 자세를 유지하세요.",
      "천으로 감싼 냉찜질을 10~20분씩 적용하세요.",
      "변형, 감각저하, 심한 통증이 있으면 응급실로 이동하세요.",
    ],
    warningSigns: ["팔다리 변형", "감각저하", "손발이 차갑거나 창백함", "뼈가 보임", "심한 통증"],
    avoidActions: ["억지로 맞추기", "마사지하기", "다친 부위로 걷거나 사용하기"],
    sourceIds: [],
  },
  {
    id: "high-fever",
    name: "고열",
    shortLabel: "고열",
    keywords: ["고열", "열", "발열", "오한", "해열", "목아픔"],
    emergencyLevel: "routine",
    recommendedDepartments: ["내과", "소아청소년과", "가정의학과"],
    firstAidSteps: [
      "수분을 조금씩 마시고 가볍고 시원한 옷차림을 유지하세요.",
      "복용 가능한 해열제는 제품 설명서나 처방에 맞춰 사용하세요.",
      "의식저하, 경련, 호흡곤란이 있으면 119 또는 응급실로 가세요.",
    ],
    warningSigns: ["의식저하", "경련", "호흡곤란", "목 경직", "3개월 미만 영아 발열"],
    avoidActions: ["찬물 목욕", "해열제 중복 복용", "탈수 상태로 방치"],
    sourceIds: ["nfa-heat"],
  },
  {
    id: "dizziness",
    name: "어지러움",
    shortLabel: "어지러움",
    keywords: ["어지러움", "현기증", "빙빙", "실신", "휘청", "기절"],
    emergencyLevel: "soon",
    recommendedDepartments: ["내과", "신경과", "이비인후과"],
    firstAidSteps: [
      "넘어지지 않도록 앉거나 누워서 쉬세요.",
      "말이 어눌하거나 한쪽 힘 빠짐, 흉통이 있는지 확인하세요.",
      "증상이 반복되거나 실신했다면 빠른 진료를 받으세요.",
    ],
    warningSigns: ["한쪽 팔다리 힘 빠짐", "말 어눌함", "실신", "흉통", "심한 두통"],
    avoidActions: ["운전하기", "혼자 계단 이용하기", "갑자기 일어서기"],
    sourceIds: [],
  },
  {
    id: "eye-ear-nose",
    name: "눈/귀/코 문제",
    shortLabel: "눈/귀/코 문제",
    keywords: ["눈", "귀", "코", "코피", "시야", "이물", "통증", "출혈"],
    emergencyLevel: "routine",
    recommendedDepartments: ["안과", "이비인후과", "응급의학과"],
    firstAidSteps: [
      "눈은 비비지 말고 이물이 보이지 않으면 억지로 빼지 마세요.",
      "코피는 고개를 약간 앞으로 숙이고 코 앞쪽을 10분 이상 누르세요.",
      "시야 이상, 심한 통증, 멈추지 않는 코피는 빠르게 진료를 받으세요.",
    ],
    warningSigns: ["시야 이상", "화학물질 노출", "눈 관통상", "30분 이상 코피", "심한 귀 통증과 어지러움"],
    avoidActions: ["눈 비비기", "코피 때 고개 뒤로 젖히기", "귀에 면봉 깊게 넣기"],
    sourceIds: ["nfa-nosebleed"],
  },
]

export const QUICK_SYMPTOM_IDS = [
  "head-injury",
  "cut-bleeding",
  "burn",
  "chest-pain",
  "breathing-difficulty",
  "abdominal-pain",
  "fracture",
  "high-fever",
  "dizziness",
  "eye-ear-nose",
]

export function getSymptom(id: string): SymptomGuide | undefined {
  return SYMPTOMS.find((symptom) => symptom.id === id)
}

export function getSources(ids: string[]): SourceRef[] {
  const required = new Set(ids)
  return OFFICIAL_SOURCES.filter((source) => required.has(source.id))
}
