import type { SourceRef, SymptomGuide } from "./types"

const COMMON_HOSPITAL_PREP = [
  "증상이 시작된 시간과 변화를 메모하기",
  "복용 중인 약 이름 또는 약 사진",
  "알레르기 여부와 기존 질환",
  "신분증 또는 보호자 연락처",
]

export const OFFICIAL_SOURCES: SourceRef[] = [
  {
    id: "nhs-ogl",
    institution: "NHS",
    title: "NHS website content under the Open Government Licence",
    url: "https://www.nhs.uk/our-policies/terms-and-conditions/",
    note: "NHS 콘텐츠는 OGL 조건을 따릅니다. 앱 문구는 원문 복제가 아닌 자체 요약으로 작성했습니다.",
  },
  {
    id: "cdc-public-domain",
    institution: "CDC",
    title: "Use of Agency Materials",
    url: "https://www.cdc.gov/other/agencymaterials.html",
    note: "CDC/ATSDR의 대부분 자료는 public domain이나 로고와 제3자 자료는 제외했습니다.",
  },
  {
    id: "ninds-bells-palsy",
    institution: "NINDS",
    title: "Bell's Palsy",
    url: "https://www.ninds.nih.gov/health-information/disorders/bells-palsy",
    note: "미국 NIH 산하 NINDS의 안면마비 관련 공개 건강정보를 참고했습니다.",
  },
]

export const SYMPTOMS: SymptomGuide[] = [
  {
    id: "minor-cut",
    name: "살짝 베였어요",
    shortLabel: "베임",
    keywords: ["베임", "상처", "칼에 베임", "종이에 베임", "피남", "피나요", "찢어짐"],
    emergencyLevel: "routine",
    recommendedDepartments: ["외과", "가정의학과"],
    firstAidSteps: ["흐르는 깨끗한 물로 상처 주변을 씻어요.", "깨끗한 거즈나 천으로 5~10분 정도 눌러 지혈해요.", "피가 멈추면 밴드나 드레싱으로 덮어요."],
    warningSigns: ["피가 10분 이상 멈추지 않음", "상처가 깊거나 벌어짐", "녹슨 물건에 찔림", "동물이나 사람에게 물림", "붓기, 고름, 열감"],
    avoidActions: ["상처 안쪽을 손으로 만지기", "붙어 있는 이물질을 억지로 빼기", "민간요법 바르기"],
    triageQuestions: [
      { id: "bleeding", question: "10분 정도 눌렀는데도 피가 계속 나나요?", ifYes: "지혈이 안 되면 외과 또는 응급실 진료가 필요할 수 있어요.", urgent: true },
      { id: "deep", question: "상처가 깊거나 벌어져 보이나요?", ifYes: "봉합이 필요할 수 있어 외과 진료를 권장해요." },
      { id: "dirty", question: "녹슨 물건, 흙, 동물/사람에게 물린 상처인가요?", ifYes: "감염과 파상풍 위험이 있어 빠른 진료를 권장해요." },
    ],
    pharmacyItems: ["멸균 거즈", "상처용 밴드", "드레싱 밴드", "생리식염수", "의료용 테이프"],
    hospitalPrepItems: [...COMMON_HOSPITAL_PREP, "다치게 한 물건 사진 또는 종류", "파상풍 예방접종 시기"],
    sourceIds: ["nhs-ogl"],
  },
  {
    id: "minor-burn",
    name: "살짝 데였어요",
    shortLabel: "화상",
    keywords: ["화상", "데임", "뜨거운 물", "고데기", "프라이팬", "물집"],
    emergencyLevel: "routine",
    recommendedDepartments: ["외과", "피부과", "가정의학과"],
    firstAidSteps: ["화상 부위를 흐르는 시원한 물에 20분 정도 식혀요.", "반지, 시계, 꽉 끼는 옷은 붓기 전에 조심히 빼요.", "깨끗한 거즈나 랩으로 느슨하게 덮어요."],
    warningSigns: ["얼굴, 손, 발, 생식기 화상", "큰 물집", "피부가 하얗거나 검게 변함", "전기나 화학물질 화상", "범위가 넓음"],
    avoidActions: ["얼음을 직접 대기", "물집 터뜨리기", "치약, 기름, 된장 바르기"],
    triageQuestions: [
      { id: "location", question: "얼굴, 손, 발, 관절 부위인가요?", ifYes: "작아 보여도 기능에 영향이 있어 빠른 진료를 권장해요." },
      { id: "blister", question: "큰 물집이 있거나 범위가 손바닥보다 넓나요?", ifYes: "화상 깊이 확인이 필요할 수 있어 진료를 권장해요." },
      { id: "chemical", question: "전기, 화학물질, 뜨거운 기름에 의한 화상인가요?", ifYes: "응급 진료가 필요할 수 있어요.", urgent: true },
    ],
    pharmacyItems: ["멸균 거즈", "화상용 드레싱", "생리식염수", "의료용 테이프"],
    hospitalPrepItems: [...COMMON_HOSPITAL_PREP, "화상 원인", "식힌 시간", "붙어 있는 옷이나 장신구 여부"],
    sourceIds: ["nhs-ogl"],
  },
  {
    id: "facial-droop",
    name: "얼굴 한쪽 마비/입 돌아감",
    shortLabel: "안면마비/구안와사",
    keywords: ["구안와사", "입 돌아감", "안면마비", "얼굴 마비", "얼굴 한쪽", "눈 안 감김", "말 어눌"],
    emergencyLevel: "soon",
    recommendedDepartments: ["신경과", "응급의학과", "이비인후과"],
    firstAidSteps: ["증상이 시작된 시간을 기록해요.", "말, 팔 힘, 보행 이상이 함께 있는지 확인해요.", "눈이 잘 감기지 않으면 눈이 마르지 않게 보호가 필요해요."],
    warningSigns: ["말이 어눌함", "한쪽 팔이나 다리 힘 빠짐", "갑작스러운 심한 두통", "어지러움과 보행 이상", "의식 저하"],
    avoidActions: ["마사지나 침으로만 버티기", "뇌졸중 가능성을 무시하기", "눈이 안 감기는데 방치하기"],
    triageQuestions: [
      { id: "stroke", question: "말이 어눌하거나 한쪽 팔/다리에 힘이 빠지나요?", ifYes: "뇌졸중 신호일 수 있어 즉시 119를 권장해요.", urgent: true },
      { id: "sudden", question: "증상이 갑자기 시작됐나요?", ifYes: "뇌졸중과 구분이 필요해 빠른 진료가 필요해요.", urgent: true },
      { id: "eye", question: "눈이 잘 감기지 않거나 눈이 마른가요?", ifYes: "눈 보호가 필요할 수 있어 진료를 권장해요." },
    ],
    pharmacyItems: ["인공눈물은 약사와 상담", "눈 보호용 거즈 또는 안대", "복용약 목록 준비"],
    hospitalPrepItems: [...COMMON_HOSPITAL_PREP, "증상 시작 시각", "말/팔/다리 이상 여부", "눈 감김 여부"],
    sourceIds: ["ninds-bells-palsy"],
  },
  {
    id: "skin-rash",
    name: "피부가 붉고 가려워요",
    shortLabel: "피부 발진",
    keywords: ["피부", "발진", "두드러기", "가려움", "붉어짐", "습진", "알레르기", "물집"],
    emergencyLevel: "routine",
    recommendedDepartments: ["피부과", "알레르기내과", "가정의학과"],
    firstAidSteps: ["새로 바른 화장품, 세제, 음식, 약을 떠올려요.", "긁지 말고 차갑게 진정시켜요.", "범위가 퍼지는지 사진이나 메모로 기록해요."],
    warningSigns: ["입술, 혀, 목이 부음", "숨쉬기 어려움", "고열", "심한 통증", "눈이나 입 안 점막까지 번짐"],
    avoidActions: ["원인 의심 물질 계속 사용", "스테로이드 연고를 오래 임의 사용", "심한 알레르기 반응을 기다리기"],
    triageQuestions: [
      { id: "breath", question: "숨쉬기 어렵거나 입술/혀가 붓나요?", ifYes: "심한 알레르기 반응일 수 있어 즉시 119 또는 응급실을 권장해요.", urgent: true },
      { id: "fever", question: "고열, 심한 통증, 물집이 함께 있나요?", ifYes: "감염이나 심한 피부질환 확인이 필요해 빠른 진료를 권장해요." },
      { id: "newdrug", question: "새 약을 먹은 뒤 전신 발진이 생겼나요?", ifYes: "약물 반응 가능성이 있어 진료 상담을 권장해요." },
    ],
    pharmacyItems: ["보습제", "가려움 완화 제품", "알레르기 약은 약사와 상담", "저자극 세정제"],
    hospitalPrepItems: [...COMMON_HOSPITAL_PREP, "발진 사진", "새로 먹은 약/음식/화장품", "발진 시작 시각"],
    sourceIds: ["nhs-ogl", "cdc-public-domain"],
  },
  {
    id: "palpitations",
    name: "심장이 두근거려요",
    shortLabel: "가슴 두근거림",
    keywords: ["심장 두근", "두근거림", "맥박", "가슴 떨림", "심장이 빨리", "부정맥"],
    emergencyLevel: "soon",
    recommendedDepartments: ["순환기내과", "내과", "응급의학과"],
    firstAidSteps: ["앉아서 쉬며 카페인, 술, 에너지음료 섭취를 떠올려요.", "맥박이 너무 빠르거나 불규칙한지 확인해요.", "가슴 통증, 실신 느낌, 호흡곤란이 있으면 바로 도움을 요청해요."],
    warningSigns: ["가슴 통증", "호흡곤란", "실신 또는 실신할 것 같음", "식은땀", "맥박이 매우 빠르거나 불규칙함"],
    avoidActions: ["운전 계속하기", "카페인이나 술 더 마시기", "처음 겪는 두근거림을 방치하기"],
    triageQuestions: [
      { id: "chest", question: "가슴 통증, 숨참, 식은땀이 함께 있나요?", ifYes: "심장 문제 가능성이 있어 119 또는 응급실을 권장해요.", urgent: true },
      { id: "faint", question: "기절했거나 기절할 것 같은 느낌이 있나요?", ifYes: "즉시 진료가 필요할 수 있어요.", urgent: true },
      { id: "new", question: "처음 겪는 증상이거나 반복되나요?", ifYes: "심전도 등 확인이 필요할 수 있어 내과/순환기내과 진료를 권장해요." },
    ],
    pharmacyItems: ["자가복용 약보다 약사에게 현재 증상 설명", "카페인 제품 확인", "복용 중인 감기약/비염약 확인"],
    hospitalPrepItems: [...COMMON_HOSPITAL_PREP, "맥박수", "두근거림 지속 시간", "카페인/술/감기약 복용 여부"],
    sourceIds: ["nhs-ogl"],
  },
  {
    id: "dizziness-vertigo",
    name: "어지럽고 빙빙 돌아요",
    shortLabel: "어지러움",
    keywords: ["어지러움", "현기증", "빙빙", "이석증", "메스꺼움", "균형", "쓰러질 것"],
    emergencyLevel: "soon",
    recommendedDepartments: ["이비인후과", "신경과", "내과"],
    firstAidSteps: ["넘어지지 않게 앉거나 누워요.", "갑자기 일어나지 말고 물을 조금씩 마셔요.", "말 어눌함, 한쪽 힘 빠짐, 심한 두통이 있는지 확인해요."],
    warningSigns: ["말이 어눌함", "한쪽 팔다리 힘 빠짐", "심한 두통", "가슴 통증", "실신"],
    avoidActions: ["운전하기", "혼자 계단 이용하기", "증상 중 음주하기"],
    triageQuestions: [
      { id: "neuro", question: "말이 어눌하거나 한쪽 힘이 빠지나요?", ifYes: "뇌졸중 신호일 수 있어 즉시 119를 권장해요.", urgent: true },
      { id: "chest", question: "가슴 통증이나 실신이 있었나요?", ifYes: "심장 문제 가능성이 있어 응급 진료를 고려하세요.", urgent: true },
      { id: "ear", question: "자세를 바꿀 때 빙빙 돌고 메스꺼운가요?", ifYes: "이석증 등 귀 문제 가능성이 있어 이비인후과 진료를 고려하세요." },
    ],
    pharmacyItems: ["멀미/어지러움 약은 약사와 상담", "수분 보충 제품", "복용 중인 혈압약 확인"],
    hospitalPrepItems: [...COMMON_HOSPITAL_PREP, "어지러움 양상", "자세 변화와 관련 여부", "청력 저하/귀 먹먹함 여부"],
    sourceIds: ["nhs-ogl"],
  },
  {
    id: "urination-pain",
    name: "소변 볼 때 아파요",
    shortLabel: "배뇨 통증",
    keywords: ["소변 통증", "오줌 아픔", "방광염", "소변 자주", "잔뇨감", "혈뇨"],
    emergencyLevel: "routine",
    recommendedDepartments: ["비뇨의학과", "산부인과", "내과"],
    firstAidSteps: ["물을 조금씩 마시고 증상 시작 시점을 기록해요.", "혈뇨, 열, 옆구리 통증이 있는지 확인해요.", "임신 가능성이 있으면 진료 때 꼭 말해요."],
    warningSigns: ["열", "옆구리 통증", "피 섞인 소변", "임신 중 증상", "소변이 거의 안 나옴"],
    avoidActions: ["항생제를 임의로 먹기", "통증을 참고 오래 버티기", "술이나 자극적인 음료 마시기"],
    triageQuestions: [
      { id: "fever", question: "열이나 옆구리 통증이 있나요?", ifYes: "신장 쪽 감염 가능성이 있어 빠른 진료를 권장해요." },
      { id: "blood", question: "피 섞인 소변이 보이나요?", ifYes: "비뇨의학과 진료를 권장해요." },
      { id: "pregnant", question: "임신 중이거나 가능성이 있나요?", ifYes: "임신 중 배뇨 통증은 빠른 진료 상담을 권장해요." },
    ],
    pharmacyItems: ["진통제/방광염 관련 제품은 약사와 상담", "수분 보충", "복용 중인 약 목록"],
    hospitalPrepItems: [...COMMON_HOSPITAL_PREP, "소변 증상 시작일", "열/옆구리 통증 여부", "임신 가능성"],
    sourceIds: ["nhs-ogl"],
  },
  {
    id: "back-pain",
    name: "허리가 아파요",
    shortLabel: "허리 통증",
    keywords: ["허리", "요통", "디스크", "다리 저림", "허리 삐끗", "좌골신경통"],
    emergencyLevel: "routine",
    recommendedDepartments: ["정형외과", "신경외과", "재활의학과"],
    firstAidSteps: ["무리한 자세를 피하고 편한 자세로 쉬어요.", "다리 힘 빠짐이나 감각 이상이 있는지 확인해요.", "배뇨/배변 이상이 있으면 바로 진료를 고려해요."],
    warningSigns: ["다리 힘 빠짐", "소변/대변 조절 어려움", "회음부 감각 이상", "큰 사고 뒤 통증", "암 병력 또는 고열"],
    avoidActions: ["강한 마사지로 버티기", "통증이 심한데 운동 계속하기", "감각 이상을 무시하기"],
    triageQuestions: [
      { id: "bladder", question: "소변/대변 조절이 어렵거나 회음부 감각이 이상한가요?", ifYes: "응급 평가가 필요할 수 있어 바로 진료를 권장해요.", urgent: true },
      { id: "weakness", question: "다리에 힘이 빠지거나 감각이 둔한가요?", ifYes: "신경 압박 가능성이 있어 빠른 진료를 권장해요." },
      { id: "trauma", question: "넘어짐이나 교통사고 뒤 생긴 통증인가요?", ifYes: "골절 확인이 필요할 수 있어 정형외과 진료를 권장해요." },
    ],
    pharmacyItems: ["파스/진통제는 약사와 상담", "냉찜질팩 또는 온찜질팩", "복용 중인 약 확인"],
    hospitalPrepItems: [...COMMON_HOSPITAL_PREP, "통증 시작 계기", "다리 저림/힘 빠짐 여부", "배뇨/배변 변화"],
    sourceIds: ["nhs-ogl"],
  },
  {
    id: "throat-voice",
    name: "목이 아프거나 목소리가 쉬었어요",
    shortLabel: "목 통증/쉼",
    keywords: ["목 아픔", "목소리 쉼", "인후통", "편도", "삼키기 아픔", "기침"],
    emergencyLevel: "routine",
    recommendedDepartments: ["이비인후과", "내과", "가정의학과"],
    firstAidSteps: ["물을 자주 마시고 목을 무리하게 쓰지 않아요.", "열, 호흡곤란, 침 삼키기 어려움이 있는지 확인해요.", "증상이 오래가면 이비인후과 진료를 고려해요."],
    warningSigns: ["숨쉬기 어려움", "침을 삼키기 어려움", "목이 심하게 부음", "고열", "쉰 목소리가 2주 이상 지속"],
    avoidActions: ["흡연", "목을 억지로 긁어내기", "항생제 임의 복용"],
    triageQuestions: [
      { id: "breath", question: "숨쉬기 어렵거나 침을 삼키기 힘든가요?", ifYes: "기도 문제 가능성이 있어 응급 진료를 고려하세요.", urgent: true },
      { id: "long", question: "쉰 목소리가 2주 이상 지속되나요?", ifYes: "성대 확인이 필요할 수 있어 이비인후과 진료를 권장해요." },
      { id: "fever", question: "고열과 심한 목 통증이 있나요?", ifYes: "감염 평가가 필요할 수 있어 진료를 권장해요." },
    ],
    pharmacyItems: ["목캔디/가글 제품은 약사와 상담", "체온계", "수분 보충 제품"],
    hospitalPrepItems: [...COMMON_HOSPITAL_PREP, "목소리 변화 기간", "열 여부", "기침/가래 동반 여부"],
    sourceIds: ["nhs-ogl"],
  },
  {
    id: "eye-red-pain",
    name: "눈이 빨갛고 아파요",
    shortLabel: "눈 충혈/통증",
    keywords: ["눈 충혈", "눈 통증", "결막염", "눈곱", "시야 흐림", "눈부심"],
    emergencyLevel: "soon",
    recommendedDepartments: ["안과", "응급의학과"],
    firstAidSteps: ["렌즈를 착용 중이면 가능한 경우 제거해요.", "눈을 비비지 말고 손을 씻어요.", "시야 변화나 강한 통증이 있으면 빠르게 진료를 받아요."],
    warningSigns: ["시야 흐림", "강한 통증", "빛을 보기 어려움", "렌즈 착용 중 통증", "외상 뒤 충혈"],
    avoidActions: ["눈 비비기", "남은 안약 임의 사용", "렌즈 계속 착용"],
    triageQuestions: [
      { id: "vision", question: "시야가 흐리거나 빛을 보기 힘든가요?", ifYes: "각막/안압 문제 가능성이 있어 빠른 안과 진료가 필요해요.", urgent: true },
      { id: "lens", question: "렌즈를 낀 상태에서 통증이 생겼나요?", ifYes: "각막 손상 가능성이 있어 안과 진료를 권장해요." },
      { id: "injury", question: "눈을 찔리거나 부딪힌 뒤 생겼나요?", ifYes: "외상 확인이 필요해 빠른 진료를 권장해요." },
    ],
    pharmacyItems: ["일회용 인공눈물", "생리식염수", "렌즈 보관 케이스"],
    hospitalPrepItems: [...COMMON_HOSPITAL_PREP, "렌즈 착용 여부", "시야 변화 여부", "사용한 안약 이름"],
    sourceIds: ["nhs-ogl"],
  },
  {
    id: "panic-anxiety",
    name: "갑자기 불안하고 숨이 막혀요",
    shortLabel: "불안/공황 느낌",
    keywords: ["공황", "불안", "숨 막힘", "과호흡", "가슴 답답", "죽을 것 같음"],
    emergencyLevel: "soon",
    recommendedDepartments: ["정신건강의학과", "내과", "응급의학과"],
    firstAidSteps: ["앉아서 천천히 숨을 고르고 주변 사람에게 도움을 요청해요.", "가슴 통증, 실신, 호흡곤란이 실제로 있는지 확인해요.", "처음 겪거나 반복되면 진료 상담을 고려해요."],
    warningSigns: ["가슴 통증", "실신", "입술이 파래짐", "자해 생각", "처음 겪는 심한 증상"],
    avoidActions: ["혼자 참기", "술로 진정시키기", "가슴 통증을 공황으로만 단정하기"],
    triageQuestions: [
      { id: "chest", question: "가슴 통증, 실신, 입술 파래짐이 있나요?", ifYes: "심장/호흡 문제와 구분이 필요해 응급 진료를 고려하세요.", urgent: true },
      { id: "selfharm", question: "스스로 해칠 것 같은 생각이 드나요?", ifYes: "즉시 주변 사람이나 119, 응급실 도움을 요청하세요.", urgent: true },
      { id: "first", question: "처음 겪는 매우 강한 증상인가요?", ifYes: "다른 원인 확인이 필요할 수 있어 진료 상담을 권장해요." },
    ],
    pharmacyItems: ["카페인 제품 피하기", "복용 중인 감기약/비염약 확인", "약은 의사/약사와 상담 후 사용"],
    hospitalPrepItems: [...COMMON_HOSPITAL_PREP, "증상이 시작된 상황", "카페인/술/약 복용 여부", "이전 공황 진단 여부"],
    sourceIds: ["nhs-ogl"],
  },
]

export const QUICK_SYMPTOM_IDS = [
  "minor-cut",
  "minor-burn",
  "facial-droop",
  "skin-rash",
  "palpitations",
  "dizziness-vertigo",
  "urination-pain",
  "back-pain",
  "throat-voice",
  "eye-red-pain",
]

export function getSymptom(id: string): SymptomGuide | undefined {
  return SYMPTOMS.find((symptom) => symptom.id === id)
}

export function getSources(ids: string[]): SourceRef[] {
  const required = new Set(ids)
  return OFFICIAL_SOURCES.filter((source) => required.has(source.id))
}

