import type { SourceRef, SymptomGuide } from "./types"

export const OFFICIAL_SOURCES: SourceRef[] = [
  {
    id: "nhs-ogl",
    institution: "NHS",
    title: "NHS website content under the Open Government Licence",
    url: "https://www.nhs.uk/our-policies/terms-and-conditions/",
    note: "NHS 콘텐츠는 별도 예외를 제외하고 OGL 조건으로 재사용 가능하며, 앱 데이터는 원문 복제가 아닌 자체 요약으로 작성했습니다.",
  },
  {
    id: "medlineplus-public-domain",
    institution: "MedlinePlus, National Library of Medicine",
    title: "Linking to and Using Content from MedlinePlus",
    url: "https://medlineplus.gov/about/using/usingcontent/",
    note: "MedlinePlus의 일부 건강 주제 요약과 연방정부 제작물은 public domain입니다. A.D.A.M. 백과, 약물 monograph, 일부 이미지는 제외했습니다.",
  },
  {
    id: "cdc-public-domain",
    institution: "CDC",
    title: "Use of Agency Materials",
    url: "https://www.cdc.gov/other/agencymaterials.html",
    note: "CDC/ATSDR의 대부분 자료는 public domain이나, 로고와 제3자 이미지/자료는 제외했습니다.",
  },
]

export const SYMPTOMS: SymptomGuide[] = [
  {
    id: "minor-cut",
    name: "살짝 베였어요",
    shortLabel: "베임",
    keywords: ["베임", "상처", "칼에 베임", "종이에 베임", "피남", "피나요", "손 베임", "찢어짐"],
    emergencyLevel: "routine",
    recommendedDepartments: ["외과", "가정의학과"],
    firstAidSteps: [
      "흐르는 깨끗한 물로 상처 주변을 씻어요.",
      "깨끗한 거즈나 천으로 5~10분 정도 눌러 지혈해요.",
      "피가 멈추면 밴드나 드레싱으로 덮고 젖으면 갈아줘요.",
    ],
    warningSigns: ["피가 10분 이상 멈추지 않음", "상처가 깊거나 벌어짐", "녹슨 물건에 찔림", "동물이나 사람에게 물림", "붓기, 고름, 열감"],
    avoidActions: ["상처 안쪽을 손으로 만지기", "소독약을 깊은 상처 안에 붓기", "붙어 있는 이물질을 억지로 빼기"],
    sourceIds: ["nhs-ogl", "medlineplus-public-domain"],
  },
  {
    id: "scrape",
    name: "까졌어요",
    shortLabel: "찰과상",
    keywords: ["까짐", "찰과상", "무릎 까짐", "팔꿈치 까짐", "넘어짐", "쓸림"],
    emergencyLevel: "routine",
    recommendedDepartments: ["외과", "가정의학과"],
    firstAidSteps: [
      "흙이나 먼지를 흐르는 물로 부드럽게 씻어내요.",
      "깨끗한 거즈로 물기를 닦고 얇은 드레싱을 붙여요.",
      "드레싱은 젖거나 더러워지면 새것으로 바꿔요.",
    ],
    warningSigns: ["상처에 흙이나 유리 조각이 남아 있음", "통증이 점점 심해짐", "붉은 부위가 퍼짐", "고름이나 열감", "파상풍 예방접종이 오래됨"],
    avoidActions: ["마른 흙을 문질러 떼기", "딱지를 계속 뜯기", "더러운 손으로 드레싱 갈기"],
    sourceIds: ["nhs-ogl", "medlineplus-public-domain"],
  },
  {
    id: "minor-burn",
    name: "살짝 데였어요",
    shortLabel: "가벼운 화상",
    keywords: ["화상", "데임", "데였", "뜨거운 물", "고데기", "프라이팬", "물집", "따가움"],
    emergencyLevel: "routine",
    recommendedDepartments: ["외과", "피부과", "가정의학과"],
    firstAidSteps: [
      "화상 부위를 흐르는 시원한 물에 20분 정도 식혀요.",
      "반지, 시계, 꽉 끼는 옷은 붓기 전에 조심히 빼요.",
      "깨끗한 거즈나 랩으로 느슨하게 덮어요.",
    ],
    warningSigns: ["얼굴, 손, 발, 생식기 화상", "큰 물집", "피부가 하얗거나 검게 변함", "전기나 화학물질 화상", "통증이 심하거나 범위가 넓음"],
    avoidActions: ["얼음을 직접 대기", "물집 터뜨리기", "치약, 기름, 된장 바르기", "피부에 붙은 옷을 억지로 떼기"],
    sourceIds: ["nhs-ogl", "medlineplus-public-domain"],
  },
  {
    id: "nosebleed",
    name: "코피가 나요",
    shortLabel: "코피",
    keywords: ["코피", "코 출혈", "피가 남", "코를 부딪힘", "코 건조"],
    emergencyLevel: "routine",
    recommendedDepartments: ["이비인후과", "가정의학과"],
    firstAidSteps: [
      "앉아서 고개를 살짝 앞으로 숙여요.",
      "코의 말랑한 부분을 10~15분 동안 계속 눌러요.",
      "입으로 숨 쉬고 피는 삼키지 말고 뱉어요.",
    ],
    warningSigns: ["20분 이상 멈추지 않음", "피가 매우 많이 남", "머리나 얼굴을 세게 부딪힌 뒤 발생", "어지러움이나 창백함", "혈액응고 관련 약 복용 중"],
    avoidActions: ["고개를 뒤로 젖히기", "코를 세게 풀기", "휴지를 깊게 밀어 넣기", "멈춘 직후 뜨거운 샤워하기"],
    sourceIds: ["nhs-ogl", "medlineplus-public-domain"],
  },
  {
    id: "sprain",
    name: "발목을 접질렸어요",
    shortLabel: "염좌",
    keywords: ["발목", "접질림", "삠", "삐끗", "염좌", "손목 삠", "붓기", "인대"],
    emergencyLevel: "routine",
    recommendedDepartments: ["정형외과"],
    firstAidSteps: [
      "다친 부위를 쉬게 하고 체중을 싣지 않아요.",
      "수건으로 감싼 냉찜질을 15~20분씩 해요.",
      "가능하면 압박 붕대와 높이 올리기로 붓기를 줄여요.",
    ],
    warningSigns: ["딛기 어려움", "모양이 변형됨", "감각이 둔함", "붓기나 통증이 빠르게 심해짐", "며칠 지나도 호전 없음"],
    avoidActions: ["바로 운동 계속하기", "강하게 마사지하기", "처음부터 뜨거운 찜질하기"],
    sourceIds: ["nhs-ogl", "medlineplus-public-domain"],
  },
  {
    id: "bruise",
    name: "멍이 들었어요",
    shortLabel: "멍/타박상",
    keywords: ["멍", "타박상", "부딪힘", "파랗게", "붓기", "통증"],
    emergencyLevel: "routine",
    recommendedDepartments: ["정형외과", "가정의학과"],
    firstAidSteps: [
      "다친 부위를 쉬게 하고 무리하게 움직이지 않아요.",
      "처음 24~48시간은 냉찜질을 짧게 반복해요.",
      "부기가 있으면 가능한 범위에서 높게 올려요.",
    ],
    warningSigns: ["통증이 심해짐", "관절을 움직이기 어려움", "멍이 매우 빠르게 커짐", "이유 없는 멍이 반복됨", "머리, 배, 가슴을 세게 부딪힘"],
    avoidActions: ["초기 뜨거운 찜질", "아픈 부위를 강하게 누르기", "통증을 참고 계속 운동하기"],
    sourceIds: ["nhs-ogl", "medlineplus-public-domain"],
  },
  {
    id: "insect-bite",
    name: "벌레에 물렸어요",
    shortLabel: "벌레 물림",
    keywords: ["벌레", "모기", "벌", "물림", "쏘임", "가려움", "부음"],
    emergencyLevel: "routine",
    recommendedDepartments: ["피부과", "가정의학과", "응급의학과"],
    firstAidSteps: [
      "비누와 물로 물린 부위를 씻어요.",
      "붓거나 가려우면 냉찜질을 해요.",
      "벌침이 보이면 카드처럼 납작한 물건으로 옆으로 밀어 제거해요.",
    ],
    warningSigns: ["입술이나 얼굴 부음", "숨쉬기 어려움", "두드러기가 전신으로 퍼짐", "어지러움", "물린 부위가 뜨겁고 아프며 붉게 퍼짐"],
    avoidActions: ["손톱으로 긁기", "벌침을 핀셋으로 세게 집어 짜기", "정체 모를 연고 바르기"],
    sourceIds: ["nhs-ogl", "cdc-public-domain"],
  },
  {
    id: "splinter",
    name: "가시가 박혔어요",
    shortLabel: "가시/이물질",
    keywords: ["가시", "나무 가시", "유리조각", "이물질", "박힘", "찔림"],
    emergencyLevel: "routine",
    recommendedDepartments: ["외과", "가정의학과"],
    firstAidSteps: [
      "손과 주변 피부를 깨끗이 씻어요.",
      "끝이 보이는 작은 가시는 깨끗한 핀셋으로 같은 방향으로 빼요.",
      "뺀 뒤에는 다시 씻고 작게 덮어 보호해요.",
    ],
    warningSigns: ["깊이 박힘", "유리나 금속 조각", "눈에 들어감", "빼낸 뒤에도 통증이 계속됨", "붓기나 고름"],
    avoidActions: ["깊은 이물질을 바늘로 파내기", "눈에 박힌 이물질 제거 시도", "더러운 도구 사용"],
    sourceIds: ["nhs-ogl", "medlineplus-public-domain"],
  },
  {
    id: "eye-irritation",
    name: "눈에 먼지가 들어갔어요",
    shortLabel: "눈 이물감",
    keywords: ["눈", "먼지", "이물감", "모래", "렌즈", "따가움", "눈물"],
    emergencyLevel: "routine",
    recommendedDepartments: ["안과"],
    firstAidSteps: [
      "손을 씻고 눈을 비비지 않아요.",
      "깨끗한 물이나 생리식염수로 부드럽게 씻어내요.",
      "렌즈를 끼고 있다면 가능한 경우 제거해요.",
    ],
    warningSigns: ["시야가 흐림", "강한 통증", "화학물질이 들어감", "금속 조각 가능성", "충혈과 통증이 지속됨"],
    avoidActions: ["눈 비비기", "면봉으로 눈동자 문지르기", "통증을 참고 렌즈 계속 착용"],
    sourceIds: ["nhs-ogl", "medlineplus-public-domain"],
  },
  {
    id: "mild-stomach-upset",
    name: "체한 것 같아요",
    shortLabel: "체함/소화불량",
    keywords: ["체함", "소화불량", "속 더부룩", "메스꺼움", "복부 팽만", "위통", "배아파", "배아픔", "속쓰림"],
    emergencyLevel: "routine",
    recommendedDepartments: ["내과", "가정의학과"],
    firstAidSteps: [
      "기름지거나 자극적인 음식은 잠시 피하고 쉬어요.",
      "물을 조금씩 마시며 상태를 봐요.",
      "통증 위치와 구토, 설사, 열이 동반되는지 확인해요.",
    ],
    warningSigns: ["극심한 복통", "오른쪽 아랫배 통증", "피 섞인 구토나 변", "가슴 통증", "반복 구토와 탈수"],
    avoidActions: ["억지로 토하기", "술 마시기", "통증이 심한데 진통제만 먹고 버티기"],
    sourceIds: ["nhs-ogl", "medlineplus-public-domain"],
  },
  {
    id: "diarrhea-vomiting",
    name: "설사나 구토가 있어요",
    shortLabel: "설사/구토",
    keywords: ["설사", "구토", "토함", "토할", "장염", "배탈", "탈수"],
    emergencyLevel: "routine",
    recommendedDepartments: ["내과", "가정의학과", "소아청소년과"],
    firstAidSteps: [
      "물을 한 번에 많이 마시지 말고 조금씩 자주 마셔요.",
      "기름진 음식과 술은 피하고 쉬어요.",
      "소변량, 입마름, 어지러움 같은 탈수 신호를 살펴요.",
    ],
    warningSigns: ["피 섞인 설사", "고열", "소변이 거의 안 나옴", "심한 어지러움", "영유아, 노인, 임신부의 반복 구토"],
    avoidActions: ["탈수 상태에서 카페인이나 술 마시기", "원인 모를 지사제 남용", "음식을 억지로 먹기"],
    sourceIds: ["nhs-ogl", "cdc-public-domain"],
  },
  {
    id: "mild-fever",
    name: "열이 나요",
    shortLabel: "발열",
    keywords: ["열", "열남", "발열", "미열", "고열", "오한", "몸살"],
    emergencyLevel: "routine",
    recommendedDepartments: ["내과", "가정의학과", "소아청소년과"],
    firstAidSteps: [
      "수분을 조금씩 자주 마시고 휴식해요.",
      "너무 두껍게 덮지 말고 편한 옷을 입어요.",
      "해열제는 제품 설명서나 처방에 맞춰 사용해요.",
    ],
    warningSigns: ["의식이 흐림", "경련", "목이 뻣뻣함", "호흡곤란", "3개월 미만 아기의 발열", "고열이 지속됨"],
    avoidActions: ["찬물 목욕", "해열제 중복 복용", "탈수 상태 방치"],
    sourceIds: ["nhs-ogl", "medlineplus-public-domain"],
  },
  {
    id: "sunburn",
    name: "햇볕에 탔어요",
    shortLabel: "햇볕 화상",
    keywords: ["햇볕", "선번", "피부 탐", "일광화상", "빨개짐", "따가움"],
    emergencyLevel: "routine",
    recommendedDepartments: ["피부과", "가정의학과"],
    firstAidSteps: [
      "그늘이나 실내로 이동해 피부를 더 이상 노출하지 않아요.",
      "시원한 물수건이나 샤워로 열감을 낮춰요.",
      "물을 마시고 피부는 자극 적은 보습제로 진정시켜요.",
    ],
    warningSigns: ["넓은 물집", "어지러움", "구토", "고열", "심한 탈수", "어린아이의 넓은 화상"],
    avoidActions: ["물집 터뜨리기", "얼음을 직접 대기", "다시 햇볕에 오래 있기"],
    sourceIds: ["nhs-ogl", "cdc-public-domain"],
  },
  {
    id: "heat-exhaustion",
    name: "더위 먹은 것 같아요",
    shortLabel: "온열질환",
    keywords: ["더위", "열사병", "열탈진", "땀", "어지러움", "두통", "탈수"],
    emergencyLevel: "soon",
    recommendedDepartments: ["응급의학과", "내과"],
    firstAidSteps: [
      "즉시 시원한 장소로 이동해 쉬어요.",
      "꽉 끼는 옷을 느슨하게 하고 물을 조금씩 마셔요.",
      "젖은 수건, 선풍기, 냉찜질로 몸을 식혀요.",
    ],
    warningSigns: ["의식이 흐림", "체온이 매우 높음", "땀이 나지 않음", "경련", "반복 구토", "상태가 빠르게 나빠짐"],
    avoidActions: ["혼자 참고 걷기", "술이나 카페인 마시기", "의식이 흐린 사람에게 억지로 물 먹이기"],
    sourceIds: ["cdc-public-domain", "nhs-ogl"],
  },
  {
    id: "headache",
    name: "머리가 아파요",
    shortLabel: "두통",
    keywords: ["두통", "머리아픔", "머리아파", "편두통", "머리 지끈", "눈 통증"],
    emergencyLevel: "routine",
    recommendedDepartments: ["신경과", "가정의학과", "내과"],
    firstAidSteps: [
      "조용하고 어두운 곳에서 쉬며 물을 마셔요.",
      "최근 수면 부족, 카페인, 스트레스, 음주 여부를 확인해요.",
      "평소 복용 가능한 진통제는 설명서에 맞춰 사용해요.",
    ],
    warningSigns: ["갑자기 번개처럼 심한 두통", "말이 어눌함", "한쪽 팔다리 힘 빠짐", "머리 부딪힌 뒤 두통", "고열과 목 경직", "시야 이상"],
    avoidActions: ["반복적으로 진통제 과다 복용", "신경 증상을 참고 기다리기", "음주로 넘기기"],
    sourceIds: ["nhs-ogl", "medlineplus-public-domain"],
  },
  {
    id: "dizziness",
    name: "어지러워요",
    shortLabel: "어지러움",
    keywords: ["어지러움", "어지러워", "어질", "현기증", "빙빙", "쓰러질 것", "기절", "휘청"],
    emergencyLevel: "soon",
    recommendedDepartments: ["내과", "신경과", "이비인후과"],
    firstAidSteps: [
      "넘어지지 않도록 앉거나 누워서 쉬어요.",
      "갑자기 일어나지 말고 물을 조금씩 마셔요.",
      "말 어눌함, 한쪽 힘 빠짐, 가슴 통증이 있는지 확인해요.",
    ],
    warningSigns: ["실신", "가슴 통증", "호흡곤란", "한쪽 팔다리 힘 빠짐", "말이 어눌함", "심한 두통"],
    avoidActions: ["운전하기", "혼자 계단 이용하기", "증상 중 음주하기"],
    sourceIds: ["nhs-ogl", "medlineplus-public-domain"],
  },
  {
    id: "menstrual-cramps",
    name: "생리통이 심해요",
    shortLabel: "생리통",
    keywords: ["생리통", "아랫배 통증", "월경통", "허리 통증", "골반통"],
    emergencyLevel: "routine",
    recommendedDepartments: ["산부인과", "가정의학과"],
    firstAidSteps: [
      "아랫배를 따뜻하게 하고 편한 자세로 쉬어요.",
      "가능하면 가벼운 스트레칭이나 산책으로 긴장을 풀어요.",
      "복용 가능한 진통제는 설명서나 처방에 맞춰 사용해요.",
    ],
    warningSigns: ["갑자기 매우 심한 통증", "임신 가능성", "심한 출혈", "발열", "평소와 전혀 다른 통증", "어지러움이나 실신"],
    avoidActions: ["통증 양상이 바뀌었는데 매번 참기", "진통제 과다 복용", "심한 출혈 방치"],
    sourceIds: ["nhs-ogl", "medlineplus-public-domain"],
  },
  {
    id: "allergic-rash",
    name: "두드러기나 가려움이 있어요",
    shortLabel: "알레르기",
    keywords: ["두드러기", "알레르기", "가려움", "발진", "붓기", "음식 알레르기"],
    emergencyLevel: "routine",
    recommendedDepartments: ["피부과", "알레르기내과", "가정의학과"],
    firstAidSteps: [
      "의심되는 음식, 약, 화장품, 벌레 물림 등 원인을 멀리해요.",
      "가려운 부위는 긁지 말고 차갑게 진정시켜요.",
      "증상 범위와 호흡, 입술 붓기 여부를 확인해요.",
    ],
    warningSigns: ["입술, 혀, 목이 부음", "숨쉬기 어려움", "어지러움", "전신 두드러기", "구토나 복통이 함께 나타남"],
    avoidActions: ["원인 의심 물질 계속 사용", "피부를 세게 긁기", "호흡 증상을 두고 기다리기"],
    sourceIds: ["cdc-public-domain", "nhs-ogl"],
  },
  {
    id: "choking-small-object",
    name: "목에 걸린 것 같아요",
    shortLabel: "목 막힘",
    keywords: ["목에 걸림", "사레", "기도 막힘", "음식 걸림", "기침", "숨 못쉼", "숨막힘", "숨차"],
    emergencyLevel: "soon",
    recommendedDepartments: ["응급의학과", "이비인후과"],
    firstAidSteps: [
      "기침을 할 수 있으면 계속 기침하게 하고 상태를 봐요.",
      "말을 못 하거나 숨을 못 쉬면 즉시 119에 연락해요.",
      "의식이 없어지면 주변에 도움을 요청하고 심폐소생술을 준비해요.",
    ],
    warningSigns: ["말을 못 함", "숨을 못 쉼", "입술이 파래짐", "의식 저하", "기침 소리가 약해짐"],
    avoidActions: ["손가락을 목 깊이 넣어 휘젓기", "물을 억지로 먹이기", "혼자 있게 두기"],
    sourceIds: ["nhs-ogl", "medlineplus-public-domain"],
  },
]

export const QUICK_SYMPTOM_IDS = [
  "minor-cut",
  "minor-burn",
  "nosebleed",
  "sprain",
  "insect-bite",
  "eye-irritation",
  "mild-stomach-upset",
  "diarrhea-vomiting",
  "mild-fever",
  "heat-exhaustion",
]

export function getSymptom(id: string): SymptomGuide | undefined {
  return SYMPTOMS.find((symptom) => symptom.id === id)
}

export function getSources(ids: string[]): SourceRef[] {
  const required = new Set(ids)
  return OFFICIAL_SOURCES.filter((source) => required.has(source.id))
}
